service: smart-membership-server
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 30
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'dev'}
plugins:
  - serverless-domain-manager
custom: ${file(./config/${self:provider.stage}.yml)}
package:
  patterns:
    - '!./**'
functions:
  Healthcheck:
    name: ${self:provider.stage}-${self:service}-healthcheck
    handler: api/healthcheck/index.handler
    description: heealthcheck
    package:
      individually: true
      patterns:
        - ./api/healthcheck/index.js
    environment:
      CORS_ORIGIN: ${self:custom.corsOrigin}
    events:
      - http:
          path: healthcheck
          method: get
          cors:
            origin: ${self:custom.corsOrigin}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

